name: "Run pru"
description: "GitHub action for pru. pru is a tool that updates pull requests branch from the base branch that contains specified files."
author: "winebarrel"
inputs:
  version:
    description: "version of pru"
    default: "v0.3.0"
    required: false
  repo:
    description: "owner/name of repository"
    default: ${{ github.repository }}
    required: false
  paths:
    description: "patterns for files included in pull requests"
    required: true
  bases:
    description: "base branches to update"
    required: false
  github-token:
    description: "GitHub access token"
    default: ${{ github.token }}
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "git-pull-request"
  color: "blue"
